version: '3.8'

services:

  # NestJS backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${TARGET}
    env_file:
      - .env
    volumes:
      - ./backend:${BACKEND_SRC}
      - ${BACKEND_SRC}/node_modules/
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      - postgres
    command: npm run start:dev

  # Angular frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ./frontend:${FRONTEND_SRC}
      - ${FRONTEND_SRC}/node_modules
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    command: ng serve --host=${HOST} --port ${FRONTEND_PORT}

  # Postgres database
  postgres:
    image: postgres:14.1
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '${PG_ADMIN_PORT}:${PG_ADMIN_PORT}'
    logging:
      driver: none
