version: '3.8'

services:
  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
      target: ${TARGET}
    env_file:
      - .env
    volumes:
      - ../../apps/backend:${BACKEND_SRC}
      - ${BACKEND_SRC}/node_modules/
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      - postgres
    command: npm run start:dev

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../../apps/frontend:${FRONTEND_SRC}
      - ${FRONTEND_SRC}/node_modules/
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    command: ng serve --host=${HOST} --port ${FRONTEND_PORT} --poll 2000

  postgres:
    image: postgres:14.1
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '${PG_ADMIN_PORT}:${PG_ADMIN_PORT}'
    logging:
      driver: none
