version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    env_file:
      - .env
    volumes:
      - ./:${BACKEND_SRC}
      - ${BACKEND_SRC}/node_modules/
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
