version: '3.8'

services:

  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
      target: ${TARGET}
    env_file:
      - .env
    volumes:
      - ${BACKEND_SRC}/node_modules/
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      - postgres
    command: npm run start:prod

  postgres:
    image: postgres:14.1
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - /var/lib/postgresql/data
