name: Node.js CI Backend

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - uses: borales/actions-yarn@v3.0.0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: yarn install
              working-directory: ./apps/backend
            - run: npm run build --if-present
              working-directory: ./apps/backend
            - run: npm run test
              working-directory: ./apps/backend
